/**
 * Language code to display name mapping
 */
export const LANGUAGE_LIST = {
	"af": "Afrikaans",
	"bg": "Bulgarian",
	"ca": "Catalan",
	"cs": "Czech",
	"cy": "Welsh",
	"da": "Danish",
	"de": "German",
	"de-AT": "German (Austria)",
	"de-CH": "German (Switzerland)",
	"de-DE": "German (Germany)",
	"el": "Greek",
	"en": "English",
	"en-AU": "English (Australia)",
	"en-CA": "English (Canada)",
	"en-GB": "English (UK)",
	"en-GB-oxendict": "English (UK, Oxford)",
	"en-US": "English (US)",
	"es": "Spanish",
	"es-AR": "Spanish (Argentina)",
	"es-ES": "Spanish (Spain)",
	"es-MX": "Spanish (Mexico)",
	"es-US": "Spanish (US)",
	"et": "Estonian",
	"fa": "Persian",
	"fo": "Faroese",
	"fr": "French",
	"fr-CA": "French (Canada)",
	"fr-FR": "French (France)",
	"he": "Hebrew",
	"hi": "Hindi",
	"hr": "Croatian",
	"hu": "Hungarian",
	"hy": "Armenian",
	"id": "Indonesian",
	"it": "Italian",
	"it-IT": "Italian (Italy)",
	"ko": "Korean",
	"lt": "Lithuanian",
	"lv": "Latvian",
	"nb": "Norwegian Bokmål",
	"nl": "Dutch",
	"pl": "Polish",
	"pt": "Portuguese",
	"pt-BR": "Portuguese (Brazil)",
	"pt-PT": "Portuguese (Portugal)",
	"ro": "Romanian",
	"ru": "Russian",
	"sh": "Serbo-Croatian",
	"sk": "Slovak",
	"sl": "Slovenian",
	"sq": "Albanian",
	"sr": "Serbian",
	"sv": "Swedish",
	"ta": "Tamil",
	"tg": "Tajik",
	"tr": "Turkish",
	"uk": "Ukrainian",
	"vi": "Vietnamese",
};
