sudo: required
dist: trusty
services: docker
language: minimal

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - yarn --link-duplicates --pure-lockfile

script:
  - yarn dist:linux

deploy:
  - yarn release --linux

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
