# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: yarn --link-duplicates --pure-lockfile
  displayName: 'Getting dependencies with Yarn'

- script: yarn run dist:linux:tar.gz
  displayName: 'Run electron-build'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
