# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

variables:
  GH_TOKEN: $(System.GH_TOKEN)

stages:
- stage:
  jobs:
  - template: jobs/electron-build.yml
    parameters:
      package: targz
  - template: jobs/electron-build.yml
    parameters:
      package: deb
  - template: jobs/electron-build.yml
    parameters:
      package: rpm
  - template: jobs/electron-build.yml
    parameters:
      package: pacman
  - template: jobs/electron-build.yml
    parameters:
      package: snap
  - template: jobs/electron-build.yml
    parameters:
      package: appimage
- stage: DeployPackages
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo deploying...
      displayName: 'Deploy bla'
