name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["IsmaelMartinez/teams-for-linux"]
assignees:
  - ismaelmartinez
body:
  - type: dropdown
    id: can-reproduce-pwa
    attributes:
      label: Can you reproduce this bug in the PWA?
      description: "If you can reproduce the bug in the PWA, it's likely a bug in the web app. Please report it to Microsoft instead"
      options:
        - "Yes"
        - "No"
        - Not applicable
      default: 0
    validations:
      required: true
  - type: input
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: What package are you using?
      options:
        - deb
        - rpm
        - snap
        - flatpak
        - AppImage
        - tar.gz
        - aur
        - macOS
        - Windows
        - Built from source
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: ex. 0.1.17
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step"
      value: |
        1.
        2.
        3.
        ...
      render: markdown
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen"
      value: |
        1.
        2.
        3.
        ...
      render: markdown
  - type: textarea
    id: debug
    attributes:
      label: Debug
      description: "When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error."
      value: |
        ```bash
        teams-for-linux --webDebug --logConfig='{}'
        ```
      render: markdown
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here that can help us understand and solve it faster. (like screenshots, etc).
