#!/usr/bin/env node

/**
 * Configuration Documentation Generator
 *
 * Reads the single source of truth for the wrapper's config options
 * (app/config/options.js) and emits:
 *   - docs-site/static/config-schema.json   (machine-readable schema)
 *   - docs-site/docs/configuration-generated.md (human-readable reference)
 *
 * Run after changing an option in app/config/options.js. CI runs this and
 * fails if the committed output differs (drift guard), so the docs and the
 * schema can never fall out of sync with the code.
 *
 * Usage: node scripts/generateConfigDocs.js
 */

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const options = require(path.join(ROOT, "app", "config", "options.js"));

const SCHEMA_OUTPUT = path.join(ROOT, "docs-site", "static", "config-schema.json");
const DOCS_OUTPUT = path.join(ROOT, "docs-site", "docs", "configuration-generated.md");

// The chromeUserAgent default embeds process.versions.chrome, which changes on
// every Electron bump (and is "undefined" under plain Node). Normalise it to a
// stable placeholder so the generated output is deterministic.
function normaliseDefault(name, value) {
  if (name === "chromeUserAgent" && typeof value === "string") {
    return value.replace(/Chrome\/[^\s]*/, "Chrome/<version>");
  }
  return value;
}

function buildSchema() {
  const list = [];
  for (const name of Object.keys(options)) {
    const def = options[name];
    list.push({
      name,
      type: def.type ?? null,
      default: normaliseDefault(name, def.default),
      description: (def.describe ?? "").replace(/\s+/g, " ").trim(),
    });
  }
  return list;
}

function renderDefaultCell(value) {
  // JSON.stringify gives quoted strings ("web", ""), serialised objects/arrays,
  // and bare numbers/booleans, which matches the existing docs convention.
  const rendered = value === undefined ? "undefined" : JSON.stringify(value);
  // Escape pipes so the value stays inside one Markdown table cell.
  return "`" + rendered.replace(/\|/g, "\\|") + "`";
}

function renderDescriptionCell(text) {
  // The description is rendered as prose (not inside a code span), so angle
  // brackets in placeholder tokens like <userData> would be parsed as JSX by
  // MDX and break the build. HTML-escape them, and escape pipes so the text
  // stays inside one table cell.
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\|/g, "\\|");
}

function generateMarkdown(schema) {
  let md = `# Configuration Options Reference (Auto-Generated)

:::note
This page is auto-generated by \`scripts/generateConfigDocs.js\` from \`app/config/options.js\`, the single source of truth for the wrapper's configuration. Do not edit it by hand. After changing an option, run \`npm run generate-config-docs\` and commit the result.
:::

For configuration examples, file locations, and platform-specific notes, see the [Configuration Options](configuration.md) guide. This reference lists every option the wrapper defines, with its type, default, and description.

**Total options**: ${schema.length}

| Option | Type | Default | Description |
|--------|------|---------|-------------|
`;
  for (const opt of schema) {
    const type = opt.type ? "`" + opt.type + "`" : "";
    md += `| \`${opt.name}\` | ${type} | ${renderDefaultCell(opt.default)} | ${renderDescriptionCell(opt.description)} |\n`;
  }
  md += `
---

*Generated by \`scripts/generateConfigDocs.js\` from \`app/config/options.js\`.*
`;
  return md;
}

function main() {
  const schema = buildSchema();

  fs.mkdirSync(path.dirname(SCHEMA_OUTPUT), { recursive: true });
  const schemaJson = JSON.stringify(
    {
      $generatedBy: "scripts/generateConfigDocs.js",
      source: "app/config/options.js",
      optionCount: schema.length,
      options: schema,
    },
    null,
    2,
  );
  fs.writeFileSync(SCHEMA_OUTPUT, schemaJson + "\n", "utf8");

  fs.writeFileSync(DOCS_OUTPUT, generateMarkdown(schema), "utf8");

  console.log(`Generated ${schema.length} options:`);
  console.log(`  ${path.relative(ROOT, SCHEMA_OUTPUT)}`);
  console.log(`  ${path.relative(ROOT, DOCS_OUTPUT)}`);
}

main();
