
  name: teams-for-linux-isma
  version: '0.2.1'
  summary: teams-for-linux
  description: |
    Unofficial Microsoft Teams client for Linux using Electron. 
    It uses the Web App and wraps it as a standalone application using Electron.

  grade: stable
  confinement: strict

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
