name: Build/release

env:
  GH_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}

on:
  push:
    branches:
      - test-git-actions
      - develop
      - master

defaults:
  run:
    shell: bash


jobs:
  release-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build
        run: yarn --link-duplicates --pure-lockfile

      - name: Release
        if: contains(github.ref, 'develop') || contains(github.ref, 'master')
        run: yarn dist:linux:deb

  release-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build
        run: yarn --link-duplicates --pure-lockfile

      - name: Release
        if: contains(github.ref, 'develop') || contains(github.ref, 'master')
        run: yarn dist:linux:rpm

  release-appimage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build
        run: yarn --link-duplicates --pure-lockfile

      - name: Release
        if: contains(github.ref, 'develop') || contains(github.ref, 'master')
        run: yarn dist:linux:appimage

  release-targz:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build
        run: yarn --link-duplicates --pure-lockfile

      - name: Release
        if: contains(github.ref, 'develop') || contains(github.ref, 'master')
        run: yarn dist:linux:targz

  release-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build
        run: yarn --link-duplicates --pure-lockfile

      - name: Release
        if: contains(github.ref, 'master')
        run: yarn dist:linux:snap

      - name: Release
        if: contains(github.ref, 'develop') || contains(github.ref, 'test-git-actions')
        run: yarn dist:linux:snap:edge
